DROP DATABASE IF EXISTS Estacionamiento;
CREATE DATABASE Estacionamiento CHARACTER SET utf8mb4;
USE Estacionamiento

CREATE TABLE lugares(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, lugar VARCHAR(100) NOT NULL
);

INSERT INTO lugares VALUES(1, 'Lugar 1')
INSERT INTO lugares VALUES(2, 'Lugar 2')
INSERT INTO lugares VALUES(3, 'Lugar 3')
INSERT INTO lugares VALUES(4, 'Lugar 4')
INSERT INTO lugares VALUES(5, 'Lugar 5')
INSERT INTO lugares VALUES(6, 'Lugar 6')
INSERT INTO lugares VALUES(7, 'Lugar 7')
INSERT INTO lugares VALUES(8, 'Lugar 8')
INSERT INTO lugares VALUES(9, 'Lugar 9')
INSERT INTO lugares VALUES(10, 'Lugar 10')
INSERT INTO lugares VALUES(11, 'Lugar 11')
INSERT INTO lugares VALUES(12, 'Lugar 12')
INSERT INTO lugares VALUES(13, 'Lugar 13')
INSERT INTO lugares VALUES(14, 'Lugar 14')
INSERT INTO lugares VALUES(15, 'Lugar 15')
INSERT INTO lugares VALUES(16, 'Lugar 16')
INSERT INTO lugares VALUES(17, 'Lugar 17')
INSERT INTO lugares VALUES(18, 'Lugar 18')
INSERT INTO lugares VALUES(19, 'Lugar 19')
INSERT INTO lugares VALUES(20, 'Lugar 20')
INSERT INTO lugares VALUES(21, 'Lugar 21')
INSERT INTO lugares VALUES(22, 'Lugar 22')
INSERT INTO lugares VALUES(23, 'Lugar 23')
INSERT INTO lugares VALUES(24, 'Lugar 24')
INSERT INTO lugares VALUES(25, 'Lugar 25')
INSERT INTO lugares VALUES(26, 'Lugar 26')
INSERT INTO lugares VALUES(27, 'Lugar 27')
INSERT INTO lugares VALUES(28, 'Lugar 28')
INSERT INTO lugares VALUES(29, 'Lugar 29')
INSERT INTO lugares VALUES(30, 'Lugar 30')
INSERT INTO lugares VALUES(31, 'Lugar 31')
INSERT INTO lugares VALUES(32, 'Lugar 32')
INSERT INTO lugares VALUES(33, 'Lugar 33')
INSERT INTO lugares VALUES(34, 'Lugar 34')
INSERT INTO lugares VALUES(35, 'Lugar 35')
INSERT INTO lugares VALUES(36, 'Lugar 36')
INSERT INTO lugares VALUES(37, 'Lugar 37')
INSERT INTO lugares VALUES(38, 'Lugar 38')
INSERT INTO lugares VALUES(39, 'Lugar 39')
INSERT INTO lugares VALUES(40, 'Lugar 40')
INSERT INTO lugares VALUES(41, 'Lugar 41')
INSERT INTO lugares VALUES(42, 'Lugar 42')
INSERT INTO lugares VALUES(43, 'Lugar 43')
INSERT INTO lugares VALUES(44, 'Lugar 44')
INSERT INTO lugares VALUES(45, 'Lugar 45')
INSERT INTO lugares VALUES(46, 'Lugar 46')
INSERT INTO lugares VALUES(47, 'Lugar 47')
INSERT INTO lugares VALUES(48, 'Lugar 48')
INSERT INTO lugares VALUES(49, 'Lugar 49')
INSERT INTO lugares VALUES(50, 'Lugar 50')
INSERT INTO lugares VALUES(51, 'Lugar 51')
INSERT INTO lugares VALUES(52, 'Lugar 52')
INSERT INTO lugares VALUES(53, 'Lugar 53')
INSERT INTO lugares VALUES(54, 'Lugar 54')
INSERT INTO lugares VALUES(55, 'Lugar 55')
INSERT INTO lugares VALUES(56, 'Lugar 56')
INSERT INTO lugares VALUES(57, 'Lugar 57')
INSERT INTO lugares VALUES(58, 'Lugar 58')
INSERT INTO lugares VALUES(59, 'Lugar 59')
INSERT INTO lugares VALUES(60, 'Lugar 60')
INSERT INTO lugares VALUES(61, 'Lugar 61')
INSERT INTO lugares VALUES(62, 'Lugar 62')
INSERT INTO lugares VALUES(63, 'Lugar 63')
INSERT INTO lugares VALUES(64, 'Lugar 64')
INSERT INTO lugares VALUES(65, 'Lugar 65')
INSERT INTO lugares VALUES(66, 'Lugar 66')
INSERT INTO lugares VALUES(67, 'Lugar 7')
INSERT INTO lugares VALUES(68, 'Lugar 68')
INSERT INTO lugares VALUES(69, 'Lugar 69')
INSERT INTO lugares VALUES(70, 'Lugar 70')
INSERT INTO lugares VALUES(71, 'Lugar 71')
INSERT INTO lugares VALUES(72, 'Lugar 72')
INSERT INTO lugares VALUES(73, 'Lugar 73')
INSERT INTO lugares VALUES(74, 'Lugar 74')
INSERT INTO lugares VALUES(75, 'Lugar 75')
INSERT INTO lugares VALUES(76, 'Lugar 76')
INSERT INTO lugares VALUES(77, 'Lugar 77')
INSERT INTO lugares VALUES(78, 'Lugar 78')
INSERT INTO lugares VALUES(79, 'Lugar 79')
INSERT INTO lugares VALUES(80, 'Lugar 80')




